### ISSUE TITLE
gulp.src(...).then is not a function

### ISSUE THREAD

**Issue by ericgrosse** [ngryman/gulp-bro#3]
I used the code you provided in the readme (while adding missing `require` statements):

```
var gulp = require('gulp');
var bro = require('gulp-bro');

gulp.task('build', () =>
  gulp.src('app.js')
    .then(bro())
    .then(gulp.dest('dist'))
)

gulp.watch('*.js', ['build'])
```

When running `gulp build` in the terminal, I get the following stack trace:

```
 TypeError: gulp.src(...).then is not a function
    at Gulp.<anonymous> (C:\Users\eric\workspace\Portfolio Sites\gulp_testing\gulpfile.js:13:6)
    at module.exports (C:\Users\eric\workspace\Portfolio Sites\gulp_testing\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\eric\workspace\Portfolio Sites\gulp_testing\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\eric\workspace\Portfolio Sites\gulp_testing\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\eric\workspace\Portfolio Sites\gulp_testing\node_modules\orchestrator\index.js:134:8)
    at C:\Users\eric\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:140:18)
```

**Comment by ngryman** [comment]
Hi,

Imports are omitted for the sake of the example.
For `then` that's a typo, it's `pipe`. I use too much *promises* lately I guess...
